-- Generated by Noctalia. Edit the template, not this file.
local M = {}

local c = {
  bg = "#17130c",
  bg_alt = "#241f18",
  bg_high = "#2e2922",
  fg = "#ebe1d5",
  fg_dim = "#d3c4b1",
  primary = "#f5bd59",
  on_primary = "#422c00",
  primary_container = "#b98828",
  on_primary_container = "#2a1b00",
  secondary = "#e0c293",
  tertiary = "#bcd070",
  error = "#ffb4ab",
  on_error = "#690005",
  outline = "#9c8f7d",
  shadow = "#000000",
  comment = "#4f4536",
  cursorline = "#39342c",
  selection = "#5a4621",
  terminal_normal_black = "#4f4536",
  terminal_normal_red = "#ffb4ab",
  terminal_normal_green = "#f5bd59",
  terminal_normal_yellow = "#e0c293",
  terminal_normal_blue = "#bcd070",
  terminal_normal_magenta = "#f5bd59",
  terminal_normal_cyan = "#e0c293",
  terminal_normal_white = "#ebe1d5",
}

local function hl(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

function M.setup()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.g.colors_name = "noctalia"
  vim.o.termguicolors = true

  hl("Normal", { fg = c.fg, bg = c.bg })
  hl("NormalFloat", { fg = c.fg, bg = c.bg_alt })
  hl("FloatBorder", { fg = c.outline, bg = c.bg_alt })
  hl("FloatTitle", { fg = c.primary, bg = c.bg_alt, bold = true })
  hl("ColorColumn", { bg = c.bg_alt })
  hl("Cursor", { fg = c.bg, bg = c.primary })
  hl("CursorLine", { bg = c.cursorline })
  hl("CursorLineNr", { fg = c.primary, bold = true })
  hl("LineNr", { fg = c.outline })
  hl("SignColumn", { fg = c.fg_dim, bg = c.bg })
  hl("Visual", { bg = c.selection })
  hl("Search", { fg = c.on_primary_container, bg = c.primary_container })
  hl("IncSearch", { fg = c.on_primary, bg = c.primary })
  hl("MatchParen", { fg = c.primary, bg = c.bg_high, bold = true })
  hl("Pmenu", { fg = c.fg, bg = c.bg_alt })
  hl("PmenuSel", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("PmenuSbar", { bg = c.bg_high })
  hl("PmenuThumb", { bg = c.primary })
  hl("WinSeparator", { fg = c.outline })
  hl("StatusLine", { fg = c.fg, bg = c.bg_high })
  hl("StatusLineNC", { fg = c.fg_dim, bg = c.bg_alt })
  hl("TabLine", { fg = c.fg_dim, bg = c.bg_alt })
  hl("TabLineSel", { fg = c.primary, bg = c.bg, bold = true })
  hl("TabLineFill", { bg = c.bg_alt })
  hl("Title", { fg = c.primary, bold = true })
  hl("Directory", { fg = c.primary })
  hl("NonText", { fg = c.outline })
  hl("SpecialKey", { fg = c.outline })

  hl("Comment", { fg = c.comment, italic = true })
  hl("Constant", { fg = c.tertiary })
  hl("String", { fg = c.terminal_normal_green })
  hl("Character", { fg = c.terminal_normal_green })
  hl("Number", { fg = c.terminal_normal_yellow })
  hl("Boolean", { fg = c.terminal_normal_yellow })
  hl("Float", { fg = c.terminal_normal_yellow })
  hl("Identifier", { fg = c.fg })
  hl("Function", { fg = c.primary })
  hl("Statement", { fg = c.secondary })
  hl("Conditional", { fg = c.secondary })
  hl("Repeat", { fg = c.secondary })
  hl("Label", { fg = c.secondary })
  hl("Operator", { fg = c.fg_dim })
  hl("Keyword", { fg = c.secondary, italic = true })
  hl("Exception", { fg = c.error })
  hl("PreProc", { fg = c.tertiary })
  hl("Include", { fg = c.secondary })
  hl("Define", { fg = c.secondary })
  hl("Macro", { fg = c.tertiary })
  hl("Type", { fg = c.terminal_normal_cyan })
  hl("StorageClass", { fg = c.terminal_normal_cyan })
  hl("Structure", { fg = c.terminal_normal_cyan })
  hl("Typedef", { fg = c.terminal_normal_cyan })
  hl("Special", { fg = c.primary })
  hl("Underlined", { fg = c.primary, underline = true })
  hl("Error", { fg = c.on_error, bg = c.error })
  hl("Todo", { fg = c.primary, bg = c.primary_container, bold = true })

  hl("DiagnosticError", { fg = c.error })
  hl("DiagnosticWarn", { fg = c.terminal_normal_yellow })
  hl("DiagnosticInfo", { fg = c.terminal_normal_blue })
  hl("DiagnosticHint", { fg = c.terminal_normal_cyan })
  hl("DiagnosticOk", { fg = c.terminal_normal_green })
  hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.bg_alt })
  hl("DiagnosticVirtualTextWarn", { fg = c.terminal_normal_yellow, bg = c.bg_alt })
  hl("DiagnosticVirtualTextInfo", { fg = c.terminal_normal_blue, bg = c.bg_alt })
  hl("DiagnosticVirtualTextHint", { fg = c.terminal_normal_cyan, bg = c.bg_alt })

  hl("@variable", { fg = c.fg })
  hl("@variable.builtin", { fg = c.tertiary })
  hl("@constant", { fg = c.tertiary })
  hl("@constant.builtin", { fg = c.tertiary })
  hl("@string", { fg = c.terminal_normal_green })
  hl("@number", { fg = c.terminal_normal_yellow })
  hl("@boolean", { fg = c.terminal_normal_yellow })
  hl("@function", { fg = c.primary })
  hl("@function.builtin", { fg = c.primary })
  hl("@keyword", { fg = c.secondary, italic = true })
  hl("@keyword.function", { fg = c.secondary, italic = true })
  hl("@type", { fg = c.terminal_normal_cyan })
  hl("@property", { fg = c.fg })
  hl("@constructor", { fg = c.terminal_normal_cyan })
  hl("@punctuation", { fg = c.fg_dim })
  hl("@comment", { link = "Comment" })

  hl("GitSignsAdd", { fg = c.terminal_normal_green })
  hl("GitSignsChange", { fg = c.terminal_normal_yellow })
  hl("GitSignsDelete", { fg = c.error })
  hl("WhichKey", { fg = c.primary })
  hl("WhichKeyDesc", { fg = c.fg })
  hl("WhichKeyGroup", { fg = c.secondary })
  hl("TelescopeNormal", { fg = c.fg, bg = c.bg_alt })
  hl("TelescopeBorder", { fg = c.outline, bg = c.bg_alt })
  hl("TelescopeSelection", { fg = c.on_primary_container, bg = c.primary_container })
  hl("NeoTreeNormal", { fg = c.fg, bg = c.bg_alt })
  hl("NeoTreeNormalNC", { fg = c.fg, bg = c.bg_alt })
  hl("NeoTreeDirectoryName", { fg = c.primary })
  hl("LazyNormal", { fg = c.fg, bg = c.bg_alt })
  hl("SnacksDashboardNormal", { fg = c.fg, bg = c.bg })
  hl("SnacksDashboardHeader", { fg = c.primary, bold = true })
  hl("SnacksDashboardIcon", { fg = c.tertiary, bold = true })
  hl("SnacksDashboardKey", { fg = c.terminal_normal_yellow, bold = true })
  hl("SnacksDashboardDesc", { fg = c.fg })
  hl("SnacksDashboardFile", { fg = c.secondary })
  hl("SnacksDashboardDir", { fg = c.outline })
  hl("SnacksDashboardFooter", { fg = c.fg_dim, italic = true })
  hl("SnacksDashboardSpecial", { fg = c.tertiary })
  hl("SnacksDashboardTitle", { fg = c.primary, bold = true })
  hl("SnacksDashboardTerminal", { fg = c.fg, bg = c.bg })
  hl("AlphaHeader", { fg = c.primary, bold = true })
  hl("AlphaButtons", { fg = c.fg })
  hl("AlphaFooter", { fg = c.fg_dim, italic = true })
  hl("DashboardHeader", { fg = c.primary, bold = true })
  hl("DashboardIcon", { fg = c.tertiary, bold = true })
  hl("DashboardKey", { fg = c.terminal_normal_yellow, bold = true })
  hl("DashboardDesc", { fg = c.fg })
  hl("DashboardFooter", { fg = c.fg_dim, italic = true })

  vim.g.terminal_color_0 = c.terminal_normal_black
  vim.g.terminal_color_1 = c.terminal_normal_red
  vim.g.terminal_color_2 = c.terminal_normal_green
  vim.g.terminal_color_3 = c.terminal_normal_yellow
  vim.g.terminal_color_4 = c.terminal_normal_blue
  vim.g.terminal_color_5 = c.terminal_normal_magenta
  vim.g.terminal_color_6 = c.terminal_normal_cyan
  vim.g.terminal_color_7 = c.terminal_normal_white
  vim.g.terminal_color_8 = c.outline
  vim.g.terminal_color_9 = c.terminal_normal_red
  vim.g.terminal_color_10 = c.terminal_normal_green
  vim.g.terminal_color_11 = c.terminal_normal_yellow
  vim.g.terminal_color_12 = c.terminal_normal_blue
  vim.g.terminal_color_13 = c.terminal_normal_magenta
  vim.g.terminal_color_14 = c.terminal_normal_cyan
  vim.g.terminal_color_15 = c.fg
end

M.setup()

return M
