color0 #4f4536
color1 #ffb4ab
color2 #f5bd59
color3 #e0c293
color4 #bcd070
color5 #f5bd59
color6 #e0c293
color7 #ebe1d5
color8 #9c8f7d
color9 #ffb4ab
color10 #f5bd59
color11 #e0c293
color12 #bcd070
color13 #f5bd59
color14 #e0c293
color15 #ebe1d5

cursor                #ebe1d5
cursor_text_color     #17130c
background            #17130c
foreground            #ebe1d5
selection_foreground  #d3c4b1
selection_background  #4f4536
active_border_color   #f5bd59
inactive_border_color #4f4536
url_color             #f5bd59

active_tab_foreground   #422c00
active_tab_background   #f5bd59
inactive_tab_foreground #d3c4b1
inactive_tab_background #4f4536
cursor_trail_color      #d3c4b1
