window_padding_width 5
hide_window_decorations yes
background_opacity 0.8
# font_family JetBrains Maple Mono 
font_size 13.5
symbol_map U+2E80-U+2EFF,U+3000-U+303F,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FF00-U+FFEF LXGW WenKai GB
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1 
cursor_shape block
shell_integration no-cursor



# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
